spring:
  profiles:
    active: development
    
management:
  endpoint:
    health:
      show-details: ALWAYS
    
server:
  port: 8082
  servlet:
    context-path: /contact-book

---

spring:
  profiles: development

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    
  datasource:
    url: jdbc:mysql://mysql:3306/db_contact_book?useSSL=false&allowPublicKeyRetrieval=true
    username: api_contact_book
    password: password
    driverClassName: com.mysql.jdbc.Driver

  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

user:
  topic: user-deleted