spring:
  profiles:
    active: development

management:
  endpoint:
    health:
      show-details: ALWAYS
  
server:
  port: 8081
  servlet:
    context-path: /contact-book

---

spring:
  profiles: development

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    
  datasource:
    url: jdbc:mysql://mysql:3306/db_user?useSSL=false&allowPublicKeyRetrieval=true
    username: api_user
    password: password
    driverClassName: com.mysql.jdbc.Driver

  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

user:
  topic: user-deleted